name: Ejercicio 1

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Saludo
        run: echo "Hola, mi nombre es TU NOMBRE COMPLETO"

      - name: Step 2 - Fecha y hora actual
        run: date

      - name: Step 3 - Sistema operativo
        run: 'echo "Sistema operativo: $RUNNER_OS"'
